project_name: dotshake
before:
  hooks:
    - go mod tidy

builds:
  - id: dotshake
    dir: cmd/dotshake
    binary: dotshake
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/Notch-Technologies/dotshake/cmd/dotshake/cmd.version={{.Version}}
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - linux
      - darwin
      # - windows
    goarch:
      - arm
      - amd64
      - arm64
      - mips
      - 386
    gomips:
      - hardfloat
      - softfloat

# *.tar.gz
archives:
  -
    builds:
      - dotshake
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md

# *.deb, *.rpm, *.apk
nfpms:
  - id: dotshake-deb
    maintainer: dev@dotshake.com
    description: dotshake
    homepage: https://dotshake.com
    bindir: /usr/bin
    builds:
      - dotshake
    formats:
      - deb
    scripts:
      preremove: "scripts/preremove.sh"

brews:
  -
    ids:
      - default
    commit_author:
      name: Dotshake
      email: dev@dotshake.com
    description: P2P mesh network using WireGuard
    tap:
      owner: Notch-Technologies
      name: homebrew-tap
      token: "{{ .Env.BREW_TAP_REPO_TOKEN }}"
      branch: main
    download_strategy: CurlDownloadStrategy
    homepage: https://dotshake.com/
    license: "BSD3"
    test: |
      system "#{bin}/{{ .ProjectName }} version"
